### ISSUE TITLE
Cannot verify calls with unknown arguments

### ISSUE THREAD

**Issue by iapicca** [felangel/mocktail#4]
**Describe the bug**
using  `mocktail: ^0.0.1-dev.4`
I'm experiencing difficulties to  `verify` `calls` in a situation where I cannot provide the arguments with `withArgs`
getting the error below 
`NoSuchMethodError: Class 'MockErrorHandler' has no instance method 'call' with matching arguments.`

 
**To Reproduce**

<details>
<summary>code sample</summary>

```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';

mixin Delegate<T> {
  T call();
}

mixin ErrorHandler {
  void call(Object e, StackTrace s);
}

class Foo {
  const Foo(this.errorHandler);
  final ErrorHandler errorHandler;
  void call(void Function() fun) {
    try {
      return fun();
    } catch (e, s) {
      errorHandler(e, s);
    }
  }
}

class MockErrorHandler extends Mock implements ErrorHandler {}

class MockDelegate<T> extends Mock implements Delegate<T> {}

void main() {
  final _errorHandler = MockErrorHandler();
  final _delegate = MockDelegate<String>();
  final _foo = Foo(_errorHandler);

  test('throw test', () {
    when(_delegate).calls('call').thenThrow('ops');
    _foo(_delegate);

    verify(_errorHandler).calls('call').times(equals(1));
  });
}

```

</details>

while seems like I cannot assign `any` to  `withArgs`

```dart
 verify(_errorHandler).calls('call').withArgs(
      positional: [any, any], // <= `Undefined name 'any'. Try correcting the name to one that is defined, or defining the name.`
    ).times(equals(1));
```

**Expected behavior**

**Logs **

<details>
<summary>logs</summary>

```bash
00:14 +0 -1: throw test [E]                                                                                                                                                                                 
  NoSuchMethodError: Class 'MockErrorHandler' has no instance method 'call' with matching arguments.
  Receiver: Instance of 'MockErrorHandler'
  Tried calling: call("ops", #0      _StubFunction.thenThrow.<anonymous closure> (package:mocktail/src/mocktail.dart:290:48)
  #1      _Stub.result (package:mocktail/src/mocktail.dart:176:19)
  #2      Mock.noSuchMethod (package:mocktail/src/mocktail.dart:59:19)
  #3      MockDelegate.call (file:///home/francesco/projects/xxx/test/widget_test.dart:5:5)
  #4      Foo.call (file:///home/francesco/projects/xxxtest/widget_test.dart:17:17)
  #5      main.<anonymous closure> (file:///home/francesco/projects/xxx/test/widget_test.dart:38:9)
  #6      Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:200:19)
  <asynchronous suspension>
  #7      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart)
  <asynchronous suspension>
  )
  Found: call(Object, StackTrace) => void
  dart:core                                 Object.noSuchMethod
  package:mocktail/src/mocktail.dart 65:18  Mock.noSuchMethod
  widget_test.dart 9:8                      MockErrorHandler.call
  widget_test.dart 19:19                    Foo.call
  widget_test.dart 38:9                     main.<fn>
  
00:14 +0 -1: Some tests failed.  
```

</details>

<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.26.0-2.0.pre.251, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-2.0.pre.251 at /home/francesco/snap/flutter/common/flutter
    • Framework revision 5bc725bea8 (8 hours ago), 2021-01-08 08:12:36 +0100
    • Engine revision 2e5833b7c5
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.141

! Doctor found issues in 1 category.

```

</details>

**Additional context**
I just started using this package, so most likely is my fault, but for the 1% chance that it's an actual bug I'm reporting it

**Comment by iapicca** [comment]
never mind
I just forgot `when(_errorHandler).calls('call').thenAnswer((any) => Object());`
