### ISSUE TITLE
Verify counts all extension functions instead of the specified one

### ISSUE THREAD

**Issue by zeshuaro** [felangel/mocktail#58]
**Describe the bug**
When using `verify` on an extension function, it failed to matches the specified function but instead matches all the functions defined in the extension. As a result, the also failed to match the specified `count` value.

I have a reproducible example with `flutter_bloc` cubits and I'm not 100% sure if this is an issue related to `mocktail` or `flutter_bloc`. Given that you maintain both packages, maybe you can help me to figure out 🙂 

**To Reproduce**
Below are the related classes/files to reproduce the issue:

<details>
  <summary>CounterCubit</summary>
  
  ```dart
import 'package:bloc/bloc.dart';
import 'package:equatable/equatable.dart';

part 'counter_state.dart';

class CounterCubit extends Cubit<CounterState> {
  CounterCubit() : super(CounterState());
}

extension CounterExt on CounterCubit {
  void add() => emit(state.copyWith(state.count + 1));

  void subtract() => emit(state.copyWith(state.count - 1));
}
  ```
</details>

<details>
  <summary>CounterState</summary>
  
  ```dart
part of 'counter_cubit.dart';

class CounterState extends Equatable {
  final int count;

  const CounterState([this.count = 0]);

  @override
  List<Object> get props => [count];

  CounterState copyWith([int? count]) {
    return CounterState(count ?? this.count);
  }
}
  ```
</details>

<details>
  <summary>CounterWidget</summary>
  
  ```dart
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

class Counter extends StatelessWidget {
  const Counter({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        ElevatedButton(
          key: const Key('counter_add'),
          onPressed: () => context.read<CounterCubit>().add(),
          child: Text('Add'),
        ),
        ElevatedButton(
          key: const Key('counter_subtract'),
          onPressed: () => context.read<CounterCubit>().subtract(),
          child: Text('Subtract'),
        ),
      ],
    );
  }
}
  ```
</details>

<details>
  <summary>CounterTest</summary>
  
  ```dart
import 'package:bloc_test/bloc_test.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';

class MockCounterCubit extends MockCubit<CounterState> implements CounterCubit {
}

class FakeCounterState extends Fake implements CounterState {}

extension PumpApp on WidgetTester {
  Future<void> pumpApp(Widget widget, CounterCubit cubit) async {
    registerFallbackValue<CounterState>(FakeCounterState());

    return pumpWidget(
      BlocProvider(
        create: (_) => cubit,
        child: MaterialApp(
          home: widget,
        ),
      ),
    );
  }
}

void main() {
  late CounterCubit cubit;

  setUpAll(() {
    registerFallbackValue<CounterState>(FakeCounterState());
  });

  setUp(() {
    cubit = MockCounterCubit();
    when(() => cubit.state).thenReturn(CounterState());
  });

  group('group', () {
    testWidgets(
      'test',
      (tester) async {
        await tester.pumpApp(Counter(), cubit);
        await tester.tap(find.byKey(Key('counter_add')));

        verify(() => cubit.add()).called(1);
      },
    );
  });
}
  ```
</details>

**Expected behavior**
With the `verify` in `CounterTest`, I was expecting that the test should go through but it didn't. It also reported that it found 2 matching calls instead of 1. I assume it matched both the `add` and `subtract` functions in the extension.

I tried moving the extension function `add` back to `CounterCubit` and it worked as expected. That's why I suspect there's something weird happening with extension functions.

**Screenshots**
N/A

**Logs**
<details>
  <summary>Test logs</summary>
  
  ```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: <1>
  Actual: <2>
Unexpected number of calls

When the exception was thrown, this was the stack:
#0      fail (package:test_api/src/frontend/expect.dart:153:31)
#1      _expect (package:test_api/src/frontend/expect.dart:148:3)
#2      expect (package:test_api/src/frontend/expect.dart:57:3)
#3      VerificationResult.called (package:mocktail/src/mocktail.dart:591:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  test
════════════════════════════════════════════════════════════════════════════════════════════════════
  ```
</details>

**Additional context**
N/A

**Comment by felangel** [comment]
Hi @zeshuaro 👋 
Thanks for opening an issue!

I was not able to reproduce the issue. The following works for me:

```dart
import 'package:bloc/bloc.dart';
import 'package:bloc_test/bloc_test.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

class Counter extends StatelessWidget {
  const Counter({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        ElevatedButton(
          key: const Key('counter_add'),
          onPressed: () => context.read<CounterCubit>().add(),
          child: Text('Add'),
        ),
        ElevatedButton(
          key: const Key('counter_subtract'),
          onPressed: () => context.read<CounterCubit>().subtract(),
          child: Text('Subtract'),
        ),
      ],
    );
  }
}

class CounterCubit extends Cubit<int> {
  CounterCubit() : super(0);
}

extension on CounterCubit {
  void add() => emit(state + 1);
  void subtract() => emit(state - 1);
}

class MockCounterCubit extends MockCubit<int> implements CounterCubit {}

extension PumpApp on WidgetTester {
  Future<void> pumpApp(Widget widget, CounterCubit cubit) async {
    return pumpWidget(
      BlocProvider(
        create: (_) => cubit,
        child: MaterialApp(home: widget),
      ),
    );
  }
}

void main() {
  late CounterCubit cubit;

  setUp(() {
    cubit = MockCounterCubit();
    when(() => cubit.state).thenReturn(0);
  });

  group('group', () {
    testWidgets('test', (tester) async {
      await tester.pumpApp(Counter(), cubit);
      await tester.tap(find.byKey(Key('counter_add')));
      verify(() => cubit.add()).called(1);
      verifyNever(() => cubit.subtract());
    });
  });
}
```

Can you check whether the above works for you?

**Comment by zeshuaro** [comment]
Thanks @felangel for looking into this. Your snippet works for me too. 

However, if you change the `CounterCubit` to extend a state class, i.e. `Cubit<CounterState>` instead of `Cubit<int>`, the issue is still there. See the code below:

```dart
import 'package:bloc/bloc.dart';
import 'package:bloc_test/bloc_test.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

class Counter extends StatelessWidget {
  const Counter({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        ElevatedButton(
          key: const Key('counter_add'),
          onPressed: () => context.read<CounterCubit>().add(),
          child: Text('Add'),
        ),
        ElevatedButton(
          key: const Key('counter_subtract'),
          onPressed: () => context.read<CounterCubit>().subtract(),
          child: Text('Subtract'),
        ),
      ],
    );
  }
}

class CounterCubit extends Cubit<CounterState> {
  CounterCubit() : super(CounterState());
}

class CounterState {
  final int count;

  const CounterState([this.count = 0]);

  CounterState copyWith([int? count]) {
    return CounterState(count ?? this.count);
  }
}

extension on CounterCubit {
  void add() => emit(state.copyWith(state.count + 1));
  void subtract() => emit(state.copyWith(state.count - 1));
}

class MockCounterCubit extends MockCubit<CounterState> implements CounterCubit {
}

class FakeCounterState extends Fake implements CounterState {}

extension PumpApp on WidgetTester {
  Future<void> pumpApp(Widget widget, CounterCubit cubit) async {
    return pumpWidget(
      BlocProvider(
        create: (_) => cubit,
        child: MaterialApp(home: widget),
      ),
    );
  }
}

void main() {
  late CounterCubit cubit;

  setUpAll(() {
    registerFallbackValue<CounterState>(FakeCounterState());
  });

  setUp(() {
    cubit = MockCounterCubit();
    when(() => cubit.state).thenReturn(CounterState());
  });

  group('group', () {
    testWidgets('test', (tester) async {
      await tester.pumpApp(Counter(), cubit);
      await tester.tap(find.byKey(Key('counter_add')));
      verify(() => cubit.add()).called(1);
      verifyNever(() => cubit.subtract());
    });
  });
}
```

I'm getting the following error with the code above:

```
The following TestFailure object was thrown running a test:
  Expected: <1>
  Actual: <2>
Unexpected number of calls

When the exception was thrown, this was the stack:
#0      fail (package:test_api/src/frontend/expect.dart:153:31)
#1      _expect (package:test_api/src/frontend/expect.dart:148:3)
#2      expect (package:test_api/src/frontend/expect.dart:57:3)
#3      VerificationResult.called (package:mocktail/src/mocktail.dart:591:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  test
```

**Comment by felangel** [comment]
Hi @zeshuaro 👋 
Sorry for the delayed response! I took a closer look and the issue is when you define a public extension the extension is actually also applied to the `Mock`.

For example:

```dart
class MyClass {}

extension on MyClass {
  void foo() {}
}

class MockMyClass extends Mock implements MyClass {}
```

In the above scenario, calling `foo` on `MockMyClass` will always invoke the real `foo()` (not a stub). As a result, it's not possible to stub/verify methods that are extensions because they will always result in the real extension being invoked. In the example you provided, I would highly recommend that you verify `emit` was called rather than trying to stub/verify the extension:

```dart
testWidgets('test', (tester) async {
    await tester.pumpApp(Counter(), cubit);
    await tester.tap(find.byKey(Key('counter_add')));
    verify(() => cubit.emit(1)).called(1);
});
```

Hope that helps 👍

**Comment by zeshuaro** [comment]
No worries @felangel. Thanks for the reply and explaining the issue to me. Your suggestion works for me and I can get my tests running now!
